GET http://localhost:5002/games


###
GET http://localhost:5002/games/f21e8109-49e1-4eba-9c59-aa62ac7b62e3

###
POST http://localhost:5002/games
Content-Type: application/json

{
  "name": "The Legend of Zelda: Breath of the Wild",
  "genre": "Action-adventure",
  "price": 594.99,
  "releaseDate": "2017-03-03"
}