GET http://localhost:5002/games


###
GET http://localhost:5002/games/af113e2f-974b-44e9-90aa-777e56f20735

###
POST http://localhost:5002/games
Content-Type: application/json

{
  "name": "The Legend of Zelda: Breath of the Wild",
  "genreId": "01522711-15d7-4218-9f03-a82d5ddab640",
  "price": 59.99,
  "releaseDate": "2017-03-03",
  "description": "An epic adventure in the world of Hyrule."
}

###
PUT http://localhost:5002/games/af113e2f-974b-44e9-90aa-777e56f20735
Content-Type: application/json

{
  "name": "The Legend of Zelda: Breath of the Wild II",
  "genreId": "01522711-15d7-4218-9f03-a82d5ddab640",
  "price": 29.99,
  "releaseDate": "2017-03-03",
  "description": "An epic adventure in the world of Hyrule 2nd time."
}

###
DELETE http://localhost:5002/games/af113e2f-974b-44e9-90aa-777e56f20735

###
GET http://localhost:5002/genres